### ISSUE TITLE
Error at bowtie2_derep (megahit) on example data set

### ISSUE THREAD

**Issue by mhmism** [MattiaPandolfoVR/MetaPhage#50]
Hello, 

Thank you for this pipeline. I was trying to test the channel using your example dataset. I have followed the tutorial for the stable version as indicated in the documentation. I have installed using the Conda environment. 
I am receiving an error (at the bowtie2_derep (megahit) step) while trying to run the example dataset on a cluster server using sbatch:

I hope that you can guide me to fix the issue.

A copy of the error (log):
Error executing process > 'bowtie2_derep (megahit)'

Caused by:
  Process `bowtie2_derep (megahit)` terminated with an error exit status (1)

Command executed:

  bowtie2-build     --threads 16 megahit_vOTUs_consensus.fasta megahit_vOTUs_consensus.fasta_index
  bowtie2     -p 16     -x megahit_vOTUs_consensus.fasta_index     -1 SRR8652861_dephixed_R1.fastq.gz     -2 SRR8652861_dephixed_R2.fastq.gz     -S SRR8652861_megahit_vOTUs_consensus.fasta.sam 
  samtools view     -@ 16     -S -b SRR8652861_megahit_vOTUs_consensus.fasta.sam > SRR8652861_megahit_vOTUs_consensus.fasta.bam
  samtools sort     -@ 16 SRR8652861_megahit_vOTUs_consensus.fasta.bam     -o SRR8652861_megahit_vOTUs_consensus.fasta.sorted.bam
  samtools index     -@ 16 SRR8652861_megahit_vOTUs_consensus.fasta.sorted.bam
  samtools flagstat     -@ 16 SRR8652861_megahit_vOTUs_consensus.fasta.sorted.bam > mappingstats_SRR8652861_megahit_vOTUs_consensus.fasta.txt
  qualimap bamqc     -nt 16     -outdir qualimap_bamqc_SRR8652861_megahit_vOTUs_consensus.fasta.folder     -bam SRR8652861_megahit_vOTUs_consensus.fasta.sorted.bam

Command exit status:
  1

Command output:
      color: 0
      reverse: 1
  Total time for backward call to driver() for mirror index: 00:00:04
  Java memory size is set to 1200M
  Launching application...
  
  QualiMap v.2.2.2-dev
  Built on 2019-11-11 14:05
  
  Selected tool: bamqc
  Available memory (Mb): 33
  Max memory (Mb): 1258
  Starting bam qc....
  Loading sam header...
  Loading locator...
  Loading reference...
  Number of windows: 400, effective number of windows: 2168
  Chunk of reads size: 1000
  Number of threads: 16
  Processed 216 out of 2168 windows...
  Processed 432 out of 2168 windows...
  Processed 648 out of 2168 windows...
  Processed 864 out of 2168 windows...
  Processed 1080 out of 2168 windows...
  Processed 1296 out of 2168 windows...
  Processed 1512 out of 2168 windows...
  Processed 1728 out of 2168 windows...
  Processed 1944 out of 2168 windows...
  Processed 2160 out of 2168 windows...
  Total processed windows:2168
  Number of reads: 6169922
  Number of valid reads: 635378
  Number of correct strand reads:0
  
  Inside of regions...
  Num mapped reads: 635378
  Num mapped first of pair: 322271
  Num mapped second of pair: 313107
  Num singletons: 27810
  Time taken to analyze reads: 15
  Computing descriptors...
  numberOfMappedBases: 78310008
  referenceSize: 17623649
  numberOfSequencedBases: 78296311
  numberOfAs: 19666957
  Computing per chromosome statistics...
  Computing histograms...
  Overall analysis time: 15
  end of bam qc
  Computing report...

Command error:
      2824935 (91.57%) aligned concordantly 0 times
      182943 (5.93%) aligned concordantly exactly 1 time
      77083 (2.50%) aligned concordantly >1 times
      ----
      2824935 pairs aligned concordantly 0 times; of these:
        26438 (0.94%) aligned discordantly 1 time
      ----
      2798497 pairs aligned 0 times concordantly or discordantly; of these:
        5596994 mates make up the pairs; of these:
          5534544 (98.88%) aligned 0 times
          27263 (0.49%) aligned exactly 1 time
          35187 (0.63%) aligned >1 times
  10.30% overall alignment rate
  [bam_sort_core] merging from 0 files and 16 in-memory blocks...
  Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.
  	at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
  	at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:102)
  	at java.base/java.security.AccessController.doPrivileged(Native Method)
  	at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:61)
  	at java.base/java.lang.Class.forName0(Native Method)
  	at java.base/java.lang.Class.forName(Class.java:315)
  	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:101)
  	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:83)
  	at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
  	at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:231)
  	at java.base/java.lang.Class.forName0(Native Method)
  	at java.base/java.lang.Class.forName(Class.java:315)
  	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:588)
  	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:583)
  	at java.base/java.security.AccessController.doPrivileged(Native Method)
  	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:582)
  	at java.desktop/sun.swing.SwingUtilities2.getSystemMnemonicKeyMask(SwingUtilities2.java:2212)
  	at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.initComponentDefaults(BasicLookAndFeel.java:1096)
  	at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.initComponentDefaults(MetalLookAndFeel.java:440)
  	at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:150)
  	at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1560)
  	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:587)
  	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:629)
  	at java.desktop/javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1404)
  	at java.desktop/javax.swing.UIManager.initialize(UIManager.java:1517)
  	at java.desktop/javax.swing.UIManager.maybeInitialize(UIManager.java:1483)
  	at java.desktop/javax.swing.UIManager.getDefaults(UIManager.java:709)
  	at java.desktop/javax.swing.UIManager.getColor(UIManager.java:751)
  	at org.jfree.chart.JFreeChart.<clinit>(JFreeChart.java:258)
  	at org.jfree.chart.ChartFactory.createXYLineChart(ChartFactory.java:1748)
  	at org.bioinfo.ngs.qc.qualimap.beans.BamQCChart.render(BamQCChart.java:192)
  	at org.bioinfo.ngs.qc.qualimap.beans.BamQCRegionReporter.computeChartsBuffers(BamQCRegionReporter.java:673)
  	at org.bioinfo.ngs.qc.qualimap.main.BamQcTool.execute(BamQcTool.java:263)
  	at org.bioinfo.ngs.qc.qualimap.main.NgsSmartTool.run(NgsSmartTool.java:190)
  	at org.bioinfo.ngs.qc.qualimap.main.NgsSmartMain.main(NgsSmartMain.java:113)

**Comment by mhmism** [comment]
Nevermind, I figured it out. I am closing the issue.

**Comment by telatin** [comment]
Hi, I didn't understand your error, would you like, please, to post the cause and solution for the benefit of others?
Thanks for reaching out!

**Comment by mhmism** [comment]
I think this was related to X11 forwarding not being allowed on the cluster causing a problem at bowtie2_derep step. Using unset DISPLAY fixed it for me.
